routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Web', 'as' => 'web.'], function () {
    /** Pagina Inicial */
    Route::get('/', 'WebController@home')->name('home');

    /** Pagina Destaque */
    Route::get('/destaque', 'WebController@spotlight')->name('spotlight');

    /** Pagina Alugar */
    Route::get('/quero-alugar', 'WebController@rent')->name('rent');

    /** Pagina Alugar - Específica de um imóvel */
    Route::get('/quero-alugar/{slug}', 'WebController@rentProperty')->name('rentProperty');

    /** Pagina Comprar */
    Route::get('/quero-comprar', 'WebController@buy')->name('buy');

    /** Pagina Comprar - Específica de imóvel */
    Route::get('/quero-comprar/{slug}', 'WebController@buyProperty')->name('buyProperty');

    /** Pagina Pesquisa */
    Route::match(['post', 'get'],'/filtro', 'WebController@filter')->name('filter');

    /** Página de Experiências */
    Route::get('/experiencias', 'WebController@experience')->name('experience');

    /** Página de Experiências - Específica de uma categoria */
    Route::get('/experiencias/{slug}', 'WebController@experienceCategory')->name('experienceCategory');

    /** Pagina Contatos */
    Route::get('/contato', 'WebController@contact')->name('contact');
    Route::post('/contato/sendEmail', 'WebController@sendEmail')->name('sendEmail');
    Route::get('/contato/sucesso', 'WebController@sendEmailSuccess')->name('sendEmailSuccess');

});

Route::group(['prefix' => 'component', 'namespace' => 'Web', 'as' => 'component.'], function () {
    Route::post('main-filter/search', 'FilterController@search')->name('main-filter.search');
    Route::post('main-filter/category', 'FilterController@category')->name('main-filter.category');
    Route::post('main-filter/type', 'FilterController@type')->name('main-filter.type');
    Route::post('main-filter/neighborhood', 'FilterController@neighborhood')->name('main-filter.neighborhood');
    Route::post('main-filter/bedrooms', 'FilterController@bedrooms')->name('main-filter.bedrooms');
    Route::post('main-filter/suites', 'FilterController@suites')->name('main-filter.suites');
    Route::post('main-filter/bathrooms', 'FilterController@bathrooms')->name('main-filter.bathrooms');
    Route::post('main-filter/garage', 'FilterController@garage')->name('main-filter.garage');
    Route::post('main-filter/price-base', 'FilterController@priceBase')->name('main-filter.priceBase');
    Route::post('main-filter/price-limit', 'FilterController@priceLimit')->name('main-filter.priceLimit');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    /** Formulário de login */
    Route::get('/', 'AuthController@showLoginForm')->name('login');
    Route::post('login', 'AuthController@login')->name('login.do');

    /** Rotas protegidas */
    Route::group(['middleware' => ['auth']], function () {
        /** Dashboard Home */
        Route::get('home', 'AuthController@home')->name('home');

        /** Usuários */
        Route::get('users/team', 'UserController@team')->name('users.team');
        Route::resource('users', 'UserController');

        /** Empresas */
        Route::resource('companies', 'CompanyController');

        /** Imoveis */
        Route::post('properties/image-set-cover', 'PropertyController@imageSetCover')->name('properties.imageSetCover');
        Route::delete('properties/images-remove', 'PropertyController@imageRemove')->name('properties.imageRemove');
        Route::resource('properties', 'PropertyController');

        /** Contratos */
        Route::post('contracts/get-data-owner', 'ContractController@getDataOwner')->name('contracts.get.dataOwner');
        Route::post('contracts/get-data-acquirer',
            'ContractController@getDataAcquirer')->name('contracts.get.dataAcquirer');
        Route::post('contracts/get-data-property',
            'ContractController@getDataProperty')->name('contracts.get.dataProperty');
        Route::resource('contracts', 'ContractController');
    });

    /** Logoutr */
    Route::get('logout', 'AuthController@logout')->name('logout');
});

resources/views/admin/dashboard.blade.php
@extends('admin.master.master')

@section('content')
    <div style="flex-basis: 100%;">
        <section class="dash_content_app">
            <header class="dash_content_app_header">
                <h2 class="icon-tachometer">Dashboard</h2>
            </header>

            <div class="dash_content_app_box">
                <section class="app_dash_home_stats">
                    <article class="control radius">
                        <h4 class="icon-users">Clientes</h4>
                        <p><b>Locadores:</b> {{$lessors}}</p>
                        <p><b>Locatários:</b> {{$lesses}}</p>
                        <p><b>Time:</b> {{$team}}</p>
                    </article>

                    <article class="blog radius">
                        <h4 class="icon-home">Imóveis</h4>
                        <p><b>Disponíveis:</b> {{$propertiesAvailable}}</p>
                        <p><b>Locados:</b> {{$propertiesUnavailable}}</p>
                        <p><b>Total:</b> {{$propertiesTotal}}</p>
                    </article>

                    <article class="users radius">
                        <h4 class="icon-file-text">Contratos</h4>
                        <p><b>Pendentes:</b> {{$contractPendent}}</p>
                        <p><b>Oficializados:</b> {{$contractActive}}</p>
                        <p><b>Cancelados:</b> {{$contractCanceled}}</p>
                        <p><b>Total:</b> {{$contractTotal}}</p>
                    </article>
                </section>
            </div>
        </section>

        <section class="dash_content_app" style="margin-top: 40px;">
            <header class="dash_content_app_header">
                <h2 class="icon-tachometer">Últimos Contratos Cadastrados</h2>
            </header>

            <div class="dash_content_app_box">
                <div class="dash_content_app_box_stage">
                    <table id="dataTable" class="nowrap hover stripe" width="100" style="width: 100% !important;">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Locador</th>
                            <th>Locatário</th>
                            <th>Negócio</th>
                            <th>Início</th>
                            <th>Vigência</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($contracts as $contract)
                            <tr>
                                <td>
                                    <a href="{{route('admin.contracts.edit',['contract' => $contract->id])}}" class="text-orange">{{$contract->id}}</a>
                                </td>
                                <td>
                                    <a href="{{route('admin.users.edit', ['user' => $contract->ownerObject->id])}}" class="text-orange">{{$contract->ownerObject->name}}</a>
                                </td>
                                <td>
                                    <a href="{{route('admin.users.edit', ['user' => $contract->acquirerObject->id])}}" class="text-orange">{{$contract->acquirerObject->name}}</a>
                                </td>
                                <td>{{($contract->sale == true ? 'Venda': 'Locação') }}</td>
                                <td>{{$contract->start_at}}</td>
                                <td>{{$contract->deadline}} mesese</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

        <section class="dash_content_app" style="margin-top: 40px;">
            <header class="dash_content_app_header">
                <h2 class="icon-tachometer">Últimos Imóveis Cadastrados</h2>
            </header>

            <div class="dash_content_app_box">
                <div class="dash_content_app_box_stage">
                    <div class="realty_list">
                        @if(!empty($properties))
                            @foreach($properties as $property)
                                <div class="realty_list_item mt-1 mb-1">
                                    <div class="realty_list_item_actions_stats">
                                        <img src="{{$property->cover()}}" alt="">
                                        <ul>
                                            @if($property->sale && !empty($property->sale_price))
                                                <li>Venda: R$ {{$property->sale_price}}</li>
                                            @endif
                                            @if($property->rent && !empty($property->rent_price))
                                                <li>Aluguel: R$ {{$property->rent_price}}</li>
                                            @endif
                                        </ul>
                                    </div>

                                    <div class="realty_list_item_content">
                                        <h4>#{{$property->id}} {{$property->type}} - {{$property->category}}</h4>

                                        <div class="realty_list_item_card">
                                            <div class="realty_list_item_card_image">
                                                <span class="icon-realty-location"></span>
                                            </div>
                                            <div class="realty_list_item_card_content">
                                                <span class="realty_list_item_description_title">Bairro:</span>
                                                <span class="realty_list_item_description_content">{{$property->neighborhood}}</span>
                                            </div>
                                        </div>

                                        <div class="realty_list_item_card">
                                            <div class="realty_list_item_card_image">
                                                <span class="icon-realty-util-area"></span>
                                            </div>
                                            <div class="realty_list_item_card_content">
                                                <span class="realty_list_item_description_title">Área Útil:</span>
                                                <span class="realty_list_item_description_content">{{$property->area_util}} m&sup2;</span>
                                            </div>
                                        </div>

                                        <div class="realty_list_item_card">
                                            <div class="realty_list_item_card_image">
                                                <span class="icon-realty-bed"></span>
                                            </div>
                                            <div class="realty_list_item_card_content">
                                                <span class="realty_list_item_description_title">Domitórios:</span>
                                                <span class="realty_list_item_description_content">{{$property->bedrooms + $property->suites}} {{(($property->bedrooms + $property->suites) > 1) ? 'Quartos' : 'Quarto'}} <br><span>{{($property->suites <= 0) ? '' : "Sendo {$property->suites} Suítes" }}</span></span>
                                            </div>
                                        </div>

                                        <div class="realty_list_item_card">
                                            <div class="realty_list_item_card_image">
                                                <span class="icon-realty-garage"></span>
                                            </div>
                                            <div class="realty_list_item_card_content">
                                                <span class="realty_list_item_description_title">Garagem:</span>
                                                <span class="realty_list_item_description_content">{{$property->garage + $property->garage_covered}} {{(($property->garage + $property->garage_covered) > 1) ? 'Vagas' : 'Vaga'}} <br><span>{{($property->garage_covered <= 0 ) ? '' : "Sendo {$property->garage_covered} cobertas"}}</span></span>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="realty_list_item_actions">
                                        <ul>
                                            <li class="icon-eye">1234 Visualizações</li>
                                        </ul>
                                        <div>
                                            <a href="" class="btn btn-blue icon-eye">Visualizar Imóvel</a>
                                            <a href="{{route('admin.properties.edit',['property' => $property->id])}}" class="btn btn-green icon-pencil-square-o">Editar Imóvel</a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        @else
                            <div class="no-content">Não foram encontrados registros!</div>
                        @endif
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="{{url(mix('backend/assets/css/reset.css'))}}"/>
    <link rel="stylesheet" href="{{url(mix('backend/assets/css/boot.css'))}}"/>
    <link rel="stylesheet" href="{{url(mix('backend/assets/css/login.css'))}}"/>
    <link rel="icon" type="image/png" href="backend/assets/images/favicon.png"/>

    <meta name="csrf-token" content="{{csrf_token()}}">

    <title>TiJackAdmin - Site Control</title>
</head>
<body>

<div class="ajax_response"></div>

<div class="dash_login">
    <div class="dash_login_left">
        <article class="dash_login_left_box">
            <header class="dash_login_box_headline">
                <div class="dash_login_box_headline_logo icon-imob icon-notext"></div>
                <h1>Login</h1>
            </header>

            <form name="login" action="{{route('admin.login.do')}}" method="post">
                <label>
                    <span class="field icon-envelope">E-mail:</span>
                    <input type="email" name="email" placeholder="Informe seu e-mail" required/>
                </label>

                <label>
                    <span class="field icon-unlock-alt">Senha:</span>
                    <input type="password" name="password_check" placeholder="Informe sua senha"/>
                </label>

                <button class="gradient gradient-orange radius icon-sign-in">Entrar</button>
            </form>

            <footer>
                <p>Desenvolvido por <a href="https://tijack.com.br">www.<b>tijack</b>.com.br</a></p>
                <p>&copy; <?= date("Y"); ?> - Todos os Direitos Reservados</p>
                <p class="dash_login_left_box_support">
                    <a target="_blank"
                       class="icon-whatsapp transition text-green"
                       href="https://api.whatsapp.com/send?phone=55+77+999197302&text=Olá, preciso de ajuda com o login."
                    >Precisa de Suporte?</a>
                </p>
            </footer>
        </article>
    </div>

    <div class="dash_login_right"></div>

</div>

<script src="{{url(mix('backend/assets/js/jquery.js'))}}"></script>
<script src="{{url(mix('backend/assets/js/login.js'))}}"></script>

</body>
</html>