routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Web', 'as' => 'web.'], function () {
    /** Pagina Inicial */
    Route::get('/', 'WebController@home')->name('home');

    /** Pagina Destaque */
    Route::get('/destaque', 'WebController@spotlight')->name('spotlight');

    /** Pagina Alugar */
    Route::get('/quero-alugar', 'WebController@rent')->name('rent');

    /** Pagina Alugar - Específica de um imóvel */
    Route::get('/quero-alugar/{slug}', 'WebController@rentProperty')->name('rentProperty');

    /** Pagina Comprar */
    Route::get('/quero-comprar', 'WebController@buy')->name('buy');

    /** Pagina Comprar - Específica de imóvel */
    Route::get('/quero-comprar/{slug}', 'WebController@buyProperty')->name('buyProperty');

    /** Pagina Pesquisa */
    Route::match(['post', 'get'],'/filtro', 'WebController@filter')->name('filter');

    /** Página de Experiências */
    Route::get('/experiencias', 'WebController@experience')->name('experience');

    /** Página de Experiências - Específica de uma categoria */
    Route::get('/experiencias/{slug}', 'WebController@experienceCategory')->name('experienceCategory');

    /** Pagina Contatos */
    Route::get('/contato', 'WebController@contact')->name('contact');
    Route::post('/contato/sendEmail', 'WebController@sendEmail')->name('sendEmail');
    Route::get('/contato/sucesso', 'WebController@sendEmailSuccess')->name('sendEmailSuccess');

});

Route::group(['prefix' => 'component', 'namespace' => 'Web', 'as' => 'component.'], function () {
    Route::post('main-filter/search', 'FilterController@search')->name('main-filter.search');
    Route::post('main-filter/category', 'FilterController@category')->name('main-filter.category');
    Route::post('main-filter/type', 'FilterController@type')->name('main-filter.type');
    Route::post('main-filter/neighborhood', 'FilterController@neighborhood')->name('main-filter.neighborhood');
    Route::post('main-filter/bedrooms', 'FilterController@bedrooms')->name('main-filter.bedrooms');
    Route::post('main-filter/suites', 'FilterController@suites')->name('main-filter.suites');
    Route::post('main-filter/bathrooms', 'FilterController@bathrooms')->name('main-filter.bathrooms');
    Route::post('main-filter/garage', 'FilterController@garage')->name('main-filter.garage');
    Route::post('main-filter/price-base', 'FilterController@priceBase')->name('main-filter.priceBase');
    Route::post('main-filter/price-limit', 'FilterController@priceLimit')->name('main-filter.priceLimit');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    /** Formulário de login */
    Route::get('/', 'AuthController@showLoginForm')->name('login');
    Route::post('login', 'AuthController@login')->name('login.do');

    /** Rotas protegidas */
    Route::group(['middleware' => ['auth']], function () {
        /** Dashboard Home */
        Route::get('home', 'AuthController@home')->name('home');

        /** Usuários */
        Route::get('users/team', 'UserController@team')->name('users.team');
        Route::resource('users', 'UserController');

        /** Empresas */
        Route::resource('companies', 'CompanyController');

        /** Imoveis */
        Route::post('properties/image-set-cover', 'PropertyController@imageSetCover')->name('properties.imageSetCover');
        Route::delete('properties/images-remove', 'PropertyController@imageRemove')->name('properties.imageRemove');
        Route::resource('properties', 'PropertyController');

        /** Contratos */
        Route::post('contracts/get-data-owner', 'ContractController@getDataOwner')->name('contracts.get.dataOwner');
        Route::post('contracts/get-data-acquirer',
            'ContractController@getDataAcquirer')->name('contracts.get.dataAcquirer');
        Route::post('contracts/get-data-property',
            'ContractController@getDataProperty')->name('contracts.get.dataProperty');
        Route::resource('contracts', 'ContractController');
    });

    /** Logoutr */
    Route::get('logout', 'AuthController@logout')->name('logout');
});

app/Company.php
<?php

namespace Imob;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'user',
        'social_name',
        'alias_name',
        'document_company',
        'document_company_secondary',
        'zipcode',
        'street',
        'number',
        'complement',
        'neighborhood',
        'state',
        'city',
    ];

    public function owner()
    {
        return $this->hasOne(User::class, 'id', 'user');
    }

    public function setDocumentCompanyAttribute($value)
    {
        $this->attributes['document_company'] = $this->clearFields($value);
    }
    public function getDocumentCompanyAttribute($value)
    {
        return substr($value, 0, 2). '.' . substr($value, 2, 3) . '.' . substr($value,5, 3). '/' .  substr($value,8, 4).'-'.substr($value, 12, 2);
    }

    private function clearFields(?string $param)
    {
        if (empty($param)) {
            return '';
        }

        return str_replace(['.', '-', '/', '(', ')', ' '], '', $param);
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace Imob\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Imob\Company;
use Imob\Http\Controllers\Controller;
use Imob\Http\Requests\Admin\CompanyRequest;
use Imob\User;

class CompanyController extends Controller
{
    private $company;

    public function __construct(Company $company)
    {
        $this->company = $company;
    }

    public function index()
    {
        $companies = $this->company->all();
        return view('admin.companies.index', [
            'companies' => $companies
        ]);
    }

    public function create(Request $request)
    {
        $users = User::orderBy('name')->get();
        $user = null;
        if (!empty($request->user)) {
            $user = User::where('id', $request->user)->first();
        }
        return view('admin.companies.create', [
            'users' => $users,
            'selected' => $user
        ]);
    }

    public function store(CompanyRequest $request)
    {
        $comanyCreate = $this->company->create($request->all());

        return redirect()->route('admin.companies.edit', [
            'company' => $comanyCreate->id
        ])->with([
            'color' => 'green',
            'message' => 'Empresa cadastrada com sucesso!'
        ]);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $company = $this->company->where('id', $id)->first();
        $users = User::orderBy('name')->get();

        return view('admin.companies.edit', [
            'company' => $company,
            'users' => $users
        ]);
    }

    public function update(CompanyRequest $request, $id)
    {
        $company = $this->company->where('id', $id)->first();
        $company->fill($request->all());

        if (!$company->save()) {
            return redirect()->back()->withInput()->withErrors();
        }
        return redirect()->route('admin.companies.edit', [
            'company' => $company->id
        ])->with([
            'color' => 'green',
            'message' => 'Empresa atualizado com sucesso!'
        ]);
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace Imob\Http\Controllers\Api;

use Illuminate\Http\Request;
use Imob\Company;
use Imob\Http\Controllers\Controller;

class CompanyController extends Controller
{

    public function index()
    {
        $companies = Company::all();
        return response()->json($companies);
    }


    public function store(Request $request)
    {
        //
    }


    public function show($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/admin/companies/create.blade.php
@extends('admin.master.master')

@section('content')
    <section class="dash_content_app">
        <header class="dash_content_app_header">
            <h2 class="icon-user-plus">Nova Empresa</h2>
            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{route('admin.home')}}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{route('admin.users.index')}}">Clientes</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{route('admin.companies.index')}}">Empresas</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        @if($errors->all())
            @foreach($errors->all() as $error)
                @message(['color' => 'red'])
                <p class="icon-asterisk">{{$error}}</p>
                @endmessage
            @endforeach
        @endif
        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">

                <form class="app_form" action="{{route('admin.companies.store')}}" method="post">
                    @csrf
                    <label class="label">
                        <span class="legend">Responsável Legal:</span>
                        <select name="user" class="select2">
                            <option value="" selected>-- Selecione --</option>
                            @foreach($users as $user)
                                <option value="{{$user->id}}" {{(!empty($selected)) && ($user->id) === $selected->id ? 'selected' : ''}}>{{$user->name}} ({{$user->document}})</option>
                            @endforeach
                        </select>
                        @if(!empty($selected->id))
                            <p style="margin-top: 4px;">
                                <a href="" class="text-orange icon-link" style="font-size: .8em;" target="_blank">Acessar Cadastro</a>
                            </p>
                        @endif
                    </label>

                    <label class="label">
                        <span class="legend">*Razão Social:</span>
                        <input type="text" name="social_name" placeholder="Razão Social" value="{{old('social_name')}}"/>
                    </label>

                    <label class="label">
                        <span class="legend">Nome Fantasia:</span>
                        <input type="text" name="alias_name" placeholder="Nome Fantasia" value="{{old('alias_name')}}"/>
                    </label>

                    <div class="label_g2">
                        <label class="label">
                            <span class="legend">CNPJ:</span>
                            <input type="tel" name="document_company" class="mask-cnpj" placeholder="CNPJ da Empresa"
                                   value="{{old('document_company')}}"/>
                        </label>

                        <label class="label">
                            <span class="legend">Inscrição Estadual:</span>
                            <input type="text" name="document_company_secondary" placeholder="Número da Inscrição" value="{{old('document_company_secondary')}}"/>
                        </label>
                    </div>

                    <div class="app_collapse">
                        <div class="app_collapse_header mt-2 collapse">
                            <h3>Endereço</h3>
                            <span class="icon-minus-circle icon-notext"></span>
                        </div>

                        <div class="app_collapse_content ">
                            <div class="label_g2">
                                <label class="label">
                                    <span class="legend">*CEP:</span>
                                    <input type="tel" name="zipcode" class="mask-zipcode zip_code_search" placeholder="Digite o CEP" value="{{old('zipcode')}}"/>
                                </label>
                            </div>

                            <label class="label">
                                <span class="legend">*Endereço:</span>
                                <input type="text" name="street" class="street" placeholder="Endereço Completo" value="{{old('street')}}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label">
                                    <span class="legend">*Número:</span>
                                    <input type="text" name="number" placeholder="Número do Endereço" value="{{old('number')}}"/>
                                </label>

                                <label class="label">
                                    <span class="legend">Complemento:</span>
                                    <input type="text" name="complement"
                                           placeholder="Completo (Opcional)" value="{{old('complement')}}"/>
                                </label>
                            </div>

                            <label class="label">
                                <span class="legend">*Bairro:</span>
                                <input type="text" name="neighborhood" class="neighborhood" placeholder="Bairro"
                                       value="{{old('neighborhood')}}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label">
                                    <span class="legend">*Estado:</span>
                                    <input type="text" name="state" class="state" placeholder="Estado" value="{{old('state')}}"/>
                                </label>

                                <label class="label">
                                    <span class="legend">*Cidade:</span>
                                    <input type="text" name="city" class="city" placeholder="Cidade" value="{{old('city')}}"/>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="text-right">
                        <button class="btn btn-large btn-green icon-check-square-o" type="submit">Criar Empresa</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/companies/edit.blade.php
@extends('admin.master.master')

@section('content')
    <section class="dash_content_app">
        <header class="dash_content_app_header">
            <h2 class="icon-user-plus">Edição Empresa</h2>
            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{route('admin.home')}}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{route('admin.users.index')}}">Clientes</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{route('admin.companies.index')}}">Empresas</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        @if($errors->all())
            @foreach($errors->all() as $error)
                @message(['color' => 'red'])
                <p class="icon-asterisk">{{$error}}</p>
                @endmessage
            @endforeach
        @endif

        @if(session()->exists('message'))
            @message(['color' => session()->get('color')])
            <p class="icon-asterisk">{{session()->get('message')}}</p>
            @endmessage
        @endif
        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">

                <form class="app_form" action="{{route('admin.companies.update', ['company' => $company->id])}}" method="post">
                    @csrf
                    @method('PUT')
                    <label class="label">
                        <span class="legend">Responsável Legal:</span>
                        <select name="user" class="select2">
                            <option value="" selected>-- Selecione --</option>
                            @foreach($users as $user)
                                <option {{$user->id === $company->user ? 'selected' : ''}} value="{{$user->id}}">{{$user->name}} ({{$user->document}})</option>
                            @endforeach
                        </select>
                        <p style="margin-top: 4px;">
                            <a href="{{route('admin.users.edit',['user' => $company->user])}}" class="text-orange icon-link" style="font-size: .8em;" target="_blank">Acessar Cadastro</a>
                        </p>
                    </label>

                    <label class="label">
                        <span class="legend">*Razão Social:</span>
                        <input type="text" name="social_name" placeholder="Razão Social" value="{{old('social_name') ?? $company->social_name}}"/>
                    </label>

                    <label class="label">
                        <span class="legend">Nome Fantasia:</span>
                        <input type="text" name="alias_name" placeholder="Nome Fantasia" value="{{old('alias_name') ?? $company->alias_name}}"/>
                    </label>

                    <div class="label_g2">
                        <label class="label">
                            <span class="legend">CNPJ:</span>
                            <input type="tel" name="document_company" class="mask-cnpj" placeholder="CNPJ da Empresa"
                                   value="{{old('document_company') ?? $company->document_company}}"/>
                        </label>

                        <label class="label">
                            <span class="legend">Inscrição Estadual:</span>
                            <input type="text" name="document_company_secondary" placeholder="Número da Inscrição" value="{{old('document_company_secondary') ?? $company->document_company_secondary}}"/>
                        </label>
                    </div>

                    <div class="app_collapse">
                        <div class="app_collapse_header mt-2 collapse">
                            <h3>Endereço</h3>
                            <span class="icon-minus-circle icon-notext"></span>
                        </div>

                        <div class="app_collapse_content ">
                            <div class="label_g2">
                                <label class="label">
                                    <span class="legend">*CEP:</span>
                                    <input type="tel" name="zipcode" class="mask-zipcode zip_code_search" placeholder="Digite o CEP" value="{{old('zipcode') ?? $company->zipcode}}"/>
                                </label>
                            </div>

                            <label class="label">
                                <span class="legend">*Endereço:</span>
                                <input type="text" name="street" class="street" placeholder="Endereço Completo" value="{{old('street') ?? $company->street}}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label">
                                    <span class="legend">*Número:</span>
                                    <input type="text" name="number" placeholder="Número do Endereço" value="{{old('number') ?? $company->number}}"/>
                                </label>

                                <label class="label">
                                    <span class="legend">Complemento:</span>
                                    <input type="text" name="complement"
                                           placeholder="Completo (Opcional)" value="{{old('complement') ?? $company->complement}}"/>
                                </label>
                            </div>

                            <label class="label">
                                <span class="legend">*Bairro:</span>
                                <input type="text" name="neighborhood" class="neighborhood" placeholder="Bairro"
                                       value="{{old('neighborhood') ?? $company->neighborhood}}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label">
                                    <span class="legend">*Estado:</span>
                                    <input type="text" name="state" class="state" placeholder="Estado" value="{{old('state') ?? $company->state}}"/>
                                </label>

                                <label class="label">
                                    <span class="legend">*Cidade:</span>
                                    <input type="text" name="city" class="city" placeholder="Cidade" value="{{old('city') ?? $company->city}}"/>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="text-right">
                        <button class="btn btn-large btn-green icon-check-square-o" type="submit">Atualizar Empresa</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/companies/filter.blade.php
<div class="dash_content_search">

    <div class="dash_content_search_close">
        <p class="text-right">
            <button class="btn btn-red icon-times icon-notext search_close"></button>
        </p>
    </div>

    <header>
        <h3 class="icon-search">Pesquisar por Empresa:</h3>
    </header>

    <main>
        <form action="">
            <label>
                <span>Nome:</span>
                <input type="text">
            </label>

            <label>
                <span>Documento:</span>
                <input type="text">
            </label>

            <div class="label_double">
                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>

                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>
            </div>

            <div class="label_double">
                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>

                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>
            </div>

            <label>
                <span>Documento:</span>
                <input type="text">
            </label>

            <button class="btn btn-block btn-large btn-green icon-search">Filtrar</button>
        </form>
    </main>
</div>

resources/views/admin/companies/index.blade.php
@extends('admin.master.master')

@section('content')
    <section class="dash_content_app">

        <header class="dash_content_app_header">
            <h2 class="icon-search">Filtro</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{route('admin.home')}}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{route('admin.users.index')}}">Clientes</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="" class="text-orange">Empresas</a></li>
                    </ul>
                </nav>

            </div>
        </header>

        @include('admin.companies.filter')

        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <table id="dataTable" class="nowrap hover stripe" width="100" style="width: 100% !important;">
                    <thead>
                    <tr>
                        <th>Razão Social</th>
                        <th>Nome Fantasia</th>
                        <th>CNPJ</th>
                        <th>IE</th>
                        <th>Responsável</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($companies as $company)
                        <tr>
                            <td>
                                <a href="{{route('admin.companies.edit', ['company' => $company->id])}}" class="text-orange">{{$company->alias_name}}</a>
                            </td>
                            <td>{{$company->social_name}}</td>
                            <td>{{$company->document_company}}</td>
                            <td>{{$company->document_company_secondary}}</td>
                            <td>
                                <a href="{{route('admin.users.edit', ['user' => $company->owner->id])}}" class="text-orange">{{$company->owner->name}}</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </section>
@endsection